export const projects = [
  {
    id: 1,
    title: "My Portfolio🌟📂",
    imageName: "my-portfolio.png",
    content: "A digital stage where my skills and journey unfold through a curated collection of projects and achievements. Explore the fusion of creativity and proficiency, as I invite you to embark on my professional narrative made with MERN Stack.",
    tags: ["React", "MongoDB", "Express", "Node JS"],
    link: "https://gvkportfolio.vercel.app/",
  },
  {
    id: 2,
    title: "StarBucks Clone☕🔄",
    imageName: "starbucks-clone.png",
    content: "Clone made on Starbucks with 10 new features including dynamic text, dynamic images changing, completely responsive, etc.",
    tags: ["React", "MongoDB", "Express", "Node JS"],
    link: "https://gvk-bucks.vercel.app/",
  },
  {
    id: 3,
    title: "Skill 2040🛠️🎓",
    imageName: "skill-2040.png",
    content: "A website that completely embraces the performance of an engineering student from A-Z. Tracking every minute detail of coding stats, course completions, performance on and giving suggestions based on an individual.",
    tags: ["React", "MongoDB", "Express", "Node JS"],
    link: "https://gvk-skill-2040.vercel.app/",
  },
  {
    id: 4,
    title: "AI Virtual Keyboard⌨️🚫",
    imageName: "ai-virtual-keyboard.png",
    content: "Enables typing virtually without any physical contact by just tapping in the air, then the words will be automatically displayed on the screen in the numpad made using Python.",
    tags: ["Python", "AI", "Machine Learning"],
    link: "https://www.linkedin.com/posts/venkatakousik_virtual-keyboard-typing-activity-7164243859428896768-smHH?utm_source=share&utm_medium=member_desktop",
  },
  {
    id: 5,
    title: "Startup Event🚀📅",
    imageName: "startup-event.png",
    content: "A website made for a startup event that contains A to Z details of everyone organizing the event and to register for the event.",
    tags: ["React", "MongoDB", "Express", "Node JS"],
    link: "https://vishva-startup.vercel.app/",
  },
  {
    id: 6,
    title: "Sports Scheduler🏅⏱️",
    imageName: "sports-scheduler.png",
    content: "A website made for organizing sports using Advanced Full Stack that leverages the art of testing along with development of the website using PERN stack.",
    tags: ["PostgreSQL", "Express", "React", "Node JS"],
    link: "https://gvk-sports-scheduler.vercel.app/",
  },
  {
    id: 7,
    title: "E-commerce Dynamo🛒💡",
    imageName: "ecommerce-dynamo.png",
    content: "An E-commerce website that immerses users in a world of real site with users adding and removing products from cart, real-time complete analytics from the admin dashboard with complete minute analytics.",
    tags: ["React", "MongoDB", "Express", "Node JS"],
    link: "https://gvk-ecommerce.vercel.app/",
  },
  {
    id: 8,
    title: "DSA Tracker💻📊",
    imageName: "dsa-tracker.jpeg",
    content: "A Virtual Keyboard that enables typing virtually without any physical contact by just tapping in the air, then the words will be automatically displayed on the screen in the numpad made using Python.",
    tags: ["Python", "AI", "Machine Learning"],
    link: "https://www.linkedin.com/posts/venkatakousik_dsatracker-websitedevelopment-bulding-activity-7175667640533749760-xJmS?utm_source=share&utm_medium=member_desktop",
  },
  {
    id: 9,
    title: "Vishnu Connect🌐👥",
    imageName: "vishnu-connect.jpeg",
    content: "Vishnu Connect is a dynamic social connection platform tailored exclusively for students, fostering a vibrant community where ideas, thoughts, and experiences are seamlessly shared. Similar to Twitter.",
    tags: ["React", "MongoDB", "Express", "Node JS"],
    link: "https://www.linkedin.com/posts/venkatakousik_fullstackdevelopment-mern-vishnu-activity-7128054408503848961-BxK6?utm_source=share&utm_medium=member_desktop",
  },
  {
    id: 10,
    title: "Customer Data📊👤",
    imageName: "customer-data.jpg",
    content: "PERN based website that retrieves customer records and creating pagination providing records based on specific search, sorting the data.",
    tags: ["PostgreSQL", "Express", "React", "Node JS"],
    link: "https://customer-pern.vercel.app/",
  }
];
