export const projects = [
  {
    id: 1,
    title: "Second Unique Portfolio",
    imageName: "my-portfolio.png",
    content: "Engineered a DSA tracker, cutting tracking time by 50% and integrating multiple coding platforms for enhanced progress visualization\nImplemented advanced security measures, achieving 100% data protection and preventing breaches.",
    tags: ["React", "MongoDB", "Express", "Node JS"],
    link: "https://gvkportfolio.vercel.app/",
  },
  {
    id: 2,
    title: "DSA Tracker",
    content: "Engineered a DSA tracker, cutting tracking time by 50% and integrating multiple coding platforms for enhanced progress visualization\nImplemented advanced security measures, achieving 100% data protection and preventing breaches ", tags: ["React", "MongoDB", "Express", "Node JS"],
    imageName: "dsaTracker.png",
    link: "https://dsa-tracker-website.vercel.app/"
  },
  {
    id: 3,
    title: "Skill 2040",
    imageName: "skill-2040.png",
    content: "A website that completely embraces the performance of an engineering student from A-Z. Tracking every minute detail of coding stats, course completions, performance on and giving suggestions based on an individual.",
    tags: ["React", "MongoDB", "Express", "Node JS"],
    link: "https://gvk-skill-2040.vercel.app/",
  },
  {
    id: 6,
    title: "Sports Scheduler",
    imageName: "sports-scheduler.png",
    content: "A website made for organizing sports using Advanced Full Stack that leverages the art of testing along with development of the website using PERN stack.",
    tags: ["PostgreSQL", "Express", "React", "Node JS"],
    link: "https://gvk-sports-scheduler.vercel.app/",
  },
  {
    id: 4,
    title: "AI Virtual Keyboard",
    imageName: "ai-virtual-keyboard.png",
    content: "Enables typing virtually without any physical contact by just tapping in the air, then the words will be automatically displayed on the screen in the numpad made using Python.",
    tags: ["Python", "AI", "Machine Learning"],
    link: "https://www.linkedin.com/posts/venkatakousik_virtual-keyboard-typing-activity-7164243859428896768-smHH?utm_source=share&utm_medium=member_desktop",
  },


  {
    id: 9,
    title: "Vishnu Connect",
    imageName: "vishnu-connect.jpeg",
    content: "Vishnu Connect is a dynamic social connection platform tailored exclusively for students, fostering a vibrant community where ideas, thoughts, and experiences are seamlessly shared. Similar to Twitter.",
    tags: ["React", "MongoDB", "Express", "Node JS"],
    link: "https://www.linkedin.com/posts/venkatakousik_fullstackdevelopment-mern-vishnu-activity-7128054408503848961-BxK6?utm_source=share&utm_medium=member_desktop",
  }, {
    id: 2,
    title: "GVK Bucks",
    imageName: "starbucks-clone.png",
    content: "Clone made on Starbucks with 10 new features including dynamic text, dynamic images changing, completely responsive, etc.",
    tags: ["React", "MongoDB", "Express", "Node JS"],
    link: "https://gvk-bucks.vercel.app/",
  }, {
    id: 7,
    title: "E-commerce Dynamo",
    imageName: "ecommerce-dynamo.png",
    content: "An E-commerce website that immerses users in a world of real site with users adding and removing products from cart, real-time complete analytics from the admin dashboard with complete minute analytics.",
    tags: ["React", "MongoDB", "Express", "Node JS"],
    link: "https://gvk-ecommerce.vercel.app/",
  },

  {
    id: 12,
    title: "Content Management Tool",
    imageName: "content.png",
    content: "Users can interact with one another with their blogs can see their blogs personalised info, interact with others posts , solves queries.",
    tags: ["React", "MongoDB", "Express", "Node JS"],
    link: "https://www.linkedin.com/posts/venkatakousik_bharatintern-contentmanagement-fullstackdeveloper-activity-7106539124232261632-Ak9t?utm_source=share&utm_medium=member_desktop",
  },
  {
    id: 13,
    title: "UI Designs ",
    imageName: "ui-designs.png",
    content: "Made mutiple amazing UI designs for startup companies adn retailer companies using Figma  ,every design will define the depth of designs the color palettes used will catch your eyes.",
    tags: ["Figma"],
    link: "https://www.linkedin.com/posts/venkatakousik_design-figma-burger-activity-7177110179715448832-ynun?utm_source=share&utm_medium=member_desktop",
  },
  {
    id: 14,
    title: "Project Management Tool",
    imageName: "project.png",
    content: "Manages tasks for employees assigning tasks seeing the progress sending personalised messages , encrypting everything so securely as big organisations are involved.",
    tags: ["React", "MongoDB", "Express", "Node JS"],
    link: "https://www.linkedin.com/posts/venkatakousik_bharatintern-fullstackdevelopment-projectmanagement-activity-7107067205242023936-45Sa?utm_source=share&utm_medium=member_desktop",
  },
  {
    id: 15,
    title: "Task Scheduler",
    imageName: "task-scheduler.png",
    content: "schedules the tasks , user can mark them as complete completed and time will be tracked exactly.",
    tags: ["React", "MongoDB", "Express", "Node JS"],
    link: "https://www.linkedin.com/posts/venkatakousik_connections-oasisinfobyte-internship-activity-7055560702698143744-7WS8?utm_source=share&utm_medium=member_desktop",
  }, {
    id: 5,
    title: "Startup Event",
    imageName: "startup-event.png",
    content: "A website made for a startup event that contains A to Z details of everyone organizing the event and to register for the event.",
    tags: ["React", "MongoDB", "Express", "Node JS"],
    link: "https://vishva-startup.vercel.app/",
  },
  {
    id: 10,
    title: "Customer Data",
    imageName: "customer-data.jpg",
    content: "PERN based website that retrieves customer records and creating pagination providing records based on specific search, sorting the data.",
    tags: ["PostgreSQL", "Express", "React", "Node JS"],
    link: "https://customer-pern.vercel.app/",
  }
];
